# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit

exclude: ^libs/

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-case-conflict
  - id: check-executables-have-shebangs
  - id: check-illegal-windows-names
  - id: check-yaml
    args: [--allow-multiple-documents]
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: mixed-line-ending
    args: [--fix,lf]
  - id: trailing-whitespace
