/* Generated by Yosys 0.8+531 (git sha1 ec2941d4, gcc 7.4.0-1ubuntu1~18.04 -fPIC -Os) */

(* cells_not_processed =  1  *)
(* src = "attrib03_localparam.v:1" *)
module bar(clk, rst, inp, out);
  (* src = "attrib03_localparam.v:20" *)
  reg _0_;
  (* src = "attrib03_localparam.v:22" *)
  wire _1_;
  (* src = "attrib03_localparam.v:15" *)
  input clk;
  (* src = "attrib03_localparam.v:17" *)
  input inp;
  (* src = "attrib03_localparam.v:18" *)
  output out;
  reg out;
  (* src = "attrib03_localparam.v:16" *)
  input rst;
  assign _1_ = ~ (* src = "attrib03_localparam.v:22" *) inp;
  always @* begin
    _0_ = out;
    casez (rst)
      1'h1:
          _0_ = 1'h0;
      default:
          _0_ = _1_;
    endcase
  end
  always @(posedge clk) begin
      out <= _0_;
  end
endmodule

(* cells_not_processed =  1  *)
(* src = "attrib03_localparam.v:26" *)
module foo(clk, rst, inp, out);
  (* src = "attrib03_localparam.v:27" *)
  input clk;
  (* src = "attrib03_localparam.v:29" *)
  input inp;
  (* src = "attrib03_localparam.v:30" *)
  output out;
  (* src = "attrib03_localparam.v:28" *)
  input rst;
  (* module_not_derived = 32'd1 *)
  (* src = "attrib03_localparam.v:32" *)
  bar bar_instance (
    clk,
    rst,
    inp,
    out
  );
endmodule
