/* Generated by Yosys 0.8+531 (git sha1 ec2941d4, gcc 7.4.0-1ubuntu1~18.04 -fPIC -Os) */

(* cells_not_processed =  1  *)
(* src = "attrib03_parameter.v:1" *)
module bar(clk, rst, inp, out);
  (* src = "attrib03_parameter.v:6" *)
  (* this_is_bar_const_param = 32'd1 *)
  parameter [31:0] BAR_CONST_PARAM = 32'd11;
  (* src = "attrib03_parameter.v:15" *)
  (* this_is_a_param_with_width = 32'd1 *)
  parameter [7:0] BAR_PARAM_WITH_WIDTH = 8'h11;
  (* src = "attrib03_parameter.v:9" *)
  (* this_is_bar_real_param = 32'd1 *)
  parameter BAR_REAL_PARAM = 0;
  (* src = "attrib03_parameter.v:12" *)
  (* this_is_string_param = 32'd1 *)
  parameter [127:0] BAR_STR_PARAM = 0;
  (* src = "attrib03_parameter.v:22" *)
  reg _0_;
  (* src = "attrib03_parameter.v:24" *)
  wire _1_;
  (* src = "attrib03_parameter.v:17" *)
  input clk;
  (* src = "attrib03_parameter.v:19" *)
  input inp;
  (* src = "attrib03_parameter.v:20" *)
  output out;
  reg out;
  (* src = "attrib03_parameter.v:18" *)
  input rst;
  assign _1_ = ~ (* src = "attrib03_parameter.v:24" *) inp;
  always @* begin
    _0_ = out;
    casez (rst)
      1'h1:
          _0_ = 1'h0;
      default:
          _0_ = _1_;
    endcase
  end
  always @(posedge clk) begin
      out <= _0_;
  end
endmodule

(* cells_not_processed =  1  *)
(* src = "attrib03_parameter.v:28" *)
module foo(clk, rst, inp, out);
  (* src = "attrib03_parameter.v:29" *)
  input clk;
  (* src = "attrib03_parameter.v:31" *)
  input inp;
  (* src = "attrib03_parameter.v:32" *)
  output out;
  (* src = "attrib03_parameter.v:30" *)
  input rst;
  (* module_not_derived = 32'd1 *)
  (* src = "attrib03_parameter.v:34" *)
  bar bar_instance (
    clk,
    rst,
    inp,
    out
  );
endmodule
