// Whole-word TDP with independent port widths. Both addresses from
// memory_libmap count 10-bit chunks; wide ports discard the low address bit.
module \$__MISTRAL_M10K_TDP_MIXED_ (PORT_A_CLK, PORT_A_CLK_EN, PORT_A_ADDR,
    PORT_A_WR_DATA, PORT_A_WR_EN, PORT_A_RD_DATA,
    PORT_B_CLK, PORT_B_CLK_EN, PORT_B_ADDR,
    PORT_B_WR_DATA, PORT_B_WR_EN, PORT_B_RD_DATA);
parameter PORT_A_WIDTH = 10;
parameter PORT_B_WIDTH = 10;
parameter INIT = 0;
localparam ASHIFT = $clog2(PORT_A_WIDTH / 10);
localparam BSHIFT = $clog2(PORT_B_WIDTH / 10);
input PORT_A_CLK, PORT_A_CLK_EN, PORT_A_WR_EN;
input PORT_B_CLK, PORT_B_CLK_EN, PORT_B_WR_EN;
input [9:0] PORT_A_ADDR, PORT_B_ADDR;
input [PORT_A_WIDTH-1:0] PORT_A_WR_DATA;
input [PORT_B_WIDTH-1:0] PORT_B_WR_DATA;
output [PORT_A_WIDTH-1:0] PORT_A_RD_DATA;
output [PORT_B_WIDTH-1:0] PORT_B_RD_DATA;
MISTRAL_M10K_TDP #(.CFG_ABITS(10-ASHIFT), .CFG_DBITS(PORT_A_WIDTH),
    .CFG_RD_ABITS(10-BSHIFT), .CFG_RD_DBITS(PORT_B_WIDTH),
    .CFG_MIXED_WIDTH(1), .INIT(INIT))
    _TECHMAP_REPLACE_ (
    .CLK1(PORT_A_CLK), .CLK2(PORT_B_CLK),
    .A1EN(PORT_A_CLK_EN), .B1EN(PORT_B_CLK_EN),
    .A1WE(PORT_A_WR_EN), .B1WE(PORT_B_WR_EN),
    .A1ADDR(PORT_A_ADDR[9:ASHIFT]), .B1ADDR(PORT_B_ADDR[9:BSHIFT]),
    .A1DATA(PORT_A_WR_DATA), .B1DATA(PORT_B_WR_DATA),
    .A1Q(PORT_A_RD_DATA), .B1Q(PORT_B_RD_DATA));
endmodule
