// Stub to invert M10K write-enable.

module \$__MISTRAL_M10K (CLK1, CLK2, A1ADDR, A1DATA, A1EN, B1ADDR, B1DATA, B1EN);

parameter INIT = 0;

parameter CFG_ABITS = 10;
parameter CFG_DBITS = 10;
parameter CFG_ENABLE_A = 1;

input CLK1, CLK2;
input [CFG_ABITS-1:0] A1ADDR, B1ADDR;
input [CFG_DBITS-1:0] A1DATA;
input [CFG_ENABLE_A-1:0] A1EN;
input B1EN;
output reg [CFG_DBITS-1:0] B1DATA;

wire a1en = CFG_ENABLE_A == 2 ? |A1EN : (CFG_DBITS == 40 ? A1EN : !A1EN);

if (CFG_ENABLE_A == 2) begin
    MISTRAL_M10K #(.INIT(INIT), .CFG_ABITS(CFG_ABITS), .CFG_DBITS(CFG_DBITS),
        .CFG_DUAL_CLOCK(1), .CFG_BYTE_ENABLE(1)) _TECHMAP_REPLACE_
        (.CLK1(CLK1), .CLK2(CLK2), .A1ADDR(A1ADDR), .A1DATA(A1DATA),
         .A1EN(a1en), .A1BE(A1EN), .B1ADDR(B1ADDR), .B1DATA(B1DATA), .B1EN(B1EN));
end else begin
    MISTRAL_M10K #(.INIT(INIT), .CFG_ABITS(CFG_ABITS), .CFG_DBITS(CFG_DBITS),
        .CFG_DUAL_CLOCK(1), .CFG_BYTE_ENABLE(0)) _TECHMAP_REPLACE_
        (.CLK1(CLK1), .CLK2(CLK2), .A1ADDR(A1ADDR), .A1DATA(A1DATA),
         .A1EN(a1en), .B1ADDR(B1ADDR), .B1DATA(B1DATA), .B1EN(B1EN));
end

endmodule
