
OBJS += passes/sat/sat.o
OBJS += passes/sat/freduce.o
OBJS += passes/sat/eval.o
OBJS += passes/sat/miter.o
OBJS += passes/sat/expose.o
OBJS += passes/sat/equiv_make.o
OBJS += passes/sat/equiv_simple.o
OBJS += passes/sat/equiv_status.o

